//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHUPA_ASSIGNEMENT_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program
    {
        public int ProgramID { get; set; }
        public string Name { get; set; }
        public string Desc { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public Nullable<bool> IsOnAirNow { get; set; }
        public string ProgramImage { get; set; }
        public Nullable<bool> IsPaidProgram { get; set; }
    }
}
